#!/bin/bash
set -euo pipefail

echo Installing initial apt packages
sudo apt -y install curl gnupg wget

echo Configuring apt repository
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

echo Updating repository
sudo apt update

echo Installing global apt packages
apt_packages=(
    git
    neofetch
    python3-venv
    python3-pip
    silversearcher-ag
    tig
    tmux
    vim
    yarn
    zsh
)
for apt_package in "${apt_packages[@]}"; do
    echo "-- Installing $apt_package"
    sudo apt -y install "$apt_package"
done

cd ~

echo Cloning dotfiles
curl -#LS https://raw.githubusercontent.com/flamecze/dotfiles/master/bootstrap.sh | bash
cd ~

echo Installing Vim plugin manager
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo Installing Vim plugins
vim +PlugInstall +qall

echo Installing Node version manager
mkdir ~/.nvm
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

echo Installing Tmux Plugin Manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

echo Installing Tmux plugins
~/.tmux/plugins/tpm/scripts/install_plugins.sh

echo Installing Antigen
curl -L git.io/antigen > ~/antigen.zsh

echo Setting zsh as default shell
chsh -s /bin/zsh

echo DONE
