#!/bin/zsh
set -euo pipefail

echo Upgrading global apt packages
sudo apt update
apt list --upgradable
sudo apt upgrade
sudo apt autoremove

echo Upgrading Vim plugins
vim +PlugUpgrade +PlugUpdate +PlugClean +qall
